'\" t
.\"     Title: FASTAQ_TRIM_Ns_AT_ENDDOC
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 10/10/2014
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "FASTAQ_TRIM_NS_AT_EN" "1" "10/10/2014" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
fastaq_trim_Ns_at_end \- Trims any Ns off each sequence in a fasta/q file
.SH "SYNOPSIS"
.sp
fastaq_trim_Ns_at_end [fasta/q in] [fasta/q out]
.SH "DESCRIPTION"
.sp
Trims any Ns off each sequence in a fasta/q file\&. Does nothing to gaps in the middle, just trims the ends
.SH "OPTIONS"
.sp
positional arguments:
.PP
\fBinfile\fR
.RS 4
Name of input fasta/q file
.RE
.PP
\fBoutfile\fR
.RS 4
Name of output fasta/q file
.RE
.sp
optional arguments
.PP
\fB\-h, \-\-help\fR
.RS 4
Show this help message
.RE
.SH "EXAMPLES"
.sp
fastaq_trim_Ns_at_end foo\&.fa trimmed_ns_foo\&.fa
.sp
fastaq_trim_Ns_at_end foo\&.fq trimmed_ns_foo\&.fq
.sp
fastaq_trim_Ns_at_end foo\&.fa\&.gz trimmed_ns_foo\&.fa\&.gz
.sp
fastaq_trim_Ns_at_end foo\&.fq\&.gz trimmed_ns_foo\&.fq\&.gz
.SH "AUTHOR"
.sp
fastaq_trim_Ns_at_end was originally written by Martin Hunt (mh12@sanger\&.ac\&.uk)
.SH "COPYING"
.sp
Wellcome Trust Sanger Institute Copyright \(co 2013 Wellcome Trust Sanger Institute This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version\&.
