#!/usr/bin/env python3

import argparse
import sys

tasks = {
    'add_indels':             'Deletes or inserts bases at given position(s)',
    'caf_to_fastq':           'Converts a CAF file to FASTQ format',
    'capillary_to_pairs':     'Converts file of capillary reads to interleaved paired file',
    'chunker':                'Splits sequences into equal sized chunks',
    'count_sequences':        'Counts the sequences in input file',
    'deinterleave':           'Splits interleaved paired file into two separate files',
    'enumerate_names':        'Renames sequences in a file, calling them 1,2,3... etc',
    'expand_nucleotides':     'Makes every combination of degenerate nucleotides',
    'fasta_to_fastq':         'Convert FASTA and .qual to FASTQ',
    'filter':                 'Filter sequences to get a subset of them',
    'get_ids':                'Get the ID of each sequence',
    'get_seq_flanking_gaps':  'Gets the sequences flanking gaps',
    'interleave':             'Interleaves two files, output is alternating between fwd/rev reads'
    'long_read_simulate':     'Simulates long reads from reference',
    'make_random_contigs':    'Make contigs of random sequence',
    'merge':                  'Converts multi sequence file to a single sequence',
    'replace_bases':          'Replaces all occurences of one letter with another',
    'reverse_complement':     'Reverse complement all sequences', 
    'scaffolds_to_contigs':   'Creates a file of contigs from a file of scaffolds',
    'search_for_seq':         'Find all exact matches to a string (and its reverse complement)',
    'sequence_trim':          'Trim exact matches to a given string off the start of every sequence',
    'split_by_base_count':    'Split multi sequence file into separate files',
    'sort_by_size':           'Sorts sequences in length order',
    'strip_illumina_suffix':  'Strips /1 or /2 off the end of every read name in a fasta/q file',
    'to_fasta':               'Converts a variety of input formats to FASTA format',
    'to_fake_qual':           'Make fake quality scores file',
    'to_mira_xml':            'Create an xml file from a file of reads, for use with Mira assembler',
    'to_orfs_gff':            'Writes a GFF file of open reading frames',
    'trim_contigs':           'Trims a set number of bases off the end of every contig',
}


def print_usage_and_exit():
    print('fastaq <command> [options]', file=sys.stderr)
    print('\nAvailable commands:\n', file=sys.stderr)
    max_task_length = max([len(x) for x in list(tasks.keys())])
    for task in tasks:
        print('{{0: <{}}}'.format(max_task_length).format(task), tasks[task], sep='  ', file=sys.stderr)
    sys.exit(1)


if len(sys.argv) == 1 or sys.argv[1] in ['-h', '-help', '--help']:
    print_usage_and_exit()

task = sys.argv.pop(1)

if task not in tasks:
    print('Task "' + task + '" not recognised. Cannot continue.\n', file=sys.stderr)
    print_usage_and_exit()


exec('import fastaq.runners.' + task)
exec('fastaq.runners.' + task + '.run("' + tasks[task] + '")')

