#!/usr/bin/env python3

import argparse
from fastaq import tasks

parser = argparse.ArgumentParser(
    description = 'Creates an xml file from a fasta/q file of reads, for use with Mira assembler',
    usage = '%(prog)s [options] <fastq_in> <xml_out>')
parser.add_argument('infile', help='Name of input fasta/q file')
parser.add_argument('xml_out', help='Name of output xml file')
options = parser.parse_args()
tasks.fastaq_to_mira_xml(options.infile, options.xml_out)
