#!/usr/bin/env python3

import argparse
from fastaq import tasks

parser = argparse.ArgumentParser(
    description = 'Creates a file of contigs from a file of scaffolds - i.e. breaks at every gap in the input',
    usage = '%(prog)s [options] <infile> <outfile>')
parser.add_argument('infile', help='Name of input fasta/q file')
parser.add_argument('outfile', help='Name of output contigs file')
options = parser.parse_args()
tasks.scaffolds_to_contigs(options.infile, options.outfile)
